### ISSUE TITLE
TXLogsResponse has the wrong format for field tx__event___tx_events

### ISSUE THREAD

**Issue by naomijub** [naomijub/transistor#8]
Field `tx__event___tx_events` is deserialized by `tx__event___tx_events: edn.get(":crux.tx.event/tx-events").map(|edn| edn.to_vec().unwrap())` which has an expected format of `Option<Vec<String>>`, like `Some(vec![":hello", "1", "3/4"])`. However the current format is:
 
```rust
Some([
  "[Key(":hello"), Int("1"), Rational("3/4")]"
])
```

* Checked with edn-rs and there it seems to work fine.

**Comment by naomijub** [comment]
Tried replacing the logic for something simpler like:

```rust
tx__event___tx_events: match edn.get(":crux.tx.event/tx-events") {
                None => None,
                Some(e) => e.to_vec()
            }
```

**Comment by otaviopace** [comment]
I was trying to debug it and by printing the `String` that `Crux` responded on `CruxClient::tx_logs`, I received this:

```edn
({:crux.tx/tx-id 0,
   :crux.tx/tx-time #inst "2020-07-21T16:30:47.611-00:00",
   :crux.tx.event/tx-events [[:crux.tx/put
                              "d72ccae848ce3a371bd313865cedc3d20b1478ca" 
                              "1828ebf4466f98ea3f5252a58734208cd0414376"]]})
```

If you look closely, `:crux.tx.event/tx-events` key is actually a vector of vectors. Since you're trying to do `Option<Vec<String>>`, I guess maybe it should be `Option<Vec<Vec<String>>>` or something similar, I am not sure yet.

I haven't tried to fix it yet since I am a bit busy, but I think this guess might help somehow, we can talk later about it too 🙂

**Comment by naomijub** [comment]
Wow it makes sense! We can try to fix this later, but this should have worked right? 
`edn.get(":crux.tx.event/tx-events").map(|edn| edn.iter().unwrap().map(|el el.to_vec().unwrap()).collect::<Vec<String>>())`

**Comment by otaviopace** [comment]
Hmmmm, honestly I am confused with this line hahahaha. Maybe we should fix it later then.

**Comment by naomijub** [comment]
It was a good first issue after all https://github.com/naomijub/transistor/pull/12
